services:
  backend:
    image: ghcr.io/highlight/highlight-backend:latest
    container_name: backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.highlight-backend.rule=Host(`lm26consys2.gf.local`)"
      - "traefik.http.services.highlight-backend.loadbalancer.server.port=8082"

    expose:
      - "8082"

    networks:
      - proxy
      - highlight

  frontend:
    image: ghcr.io/highlight/highlight-frontend:latest
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.highlight-frontend.rule=Host(`lm26consys2.gf.local`)"
      - "traefik.http.services.highlight-frontend.loadbalancer.server.port=3000"
    expose:
      - "3000"

    networks:
      - proxy
      - highlight

networks:
  proxy:
    external: true
  highlight:
    external: true